# Generated by Django 6.0.4 on 2026-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('seats', models.PositiveIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('table_type', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('bar', 'Bar')], default='square', max_length=20)),
            ],
        ),
    ]
